#!/bin/bash
#
# Instalacja Paru = AUR Helper
#sudo pacman -S --needed base-devel
#git clone https://aur.archlinux.org/paru.git
#cd paru
#makepkg -si

# Packer
# Pacman
packer='sudo pacman -S --needed --noconfirm'

$packer 7zip
$packer audacity
$packer alacritty
$packer alsa-firmware
$packer alsa-plugins
$packer alsa-utils
$packer archiso
$packer azote
$packer blueman
$packer bluez
$packer bluez-hid2hci
$packer bluez-libs
$packer bluez-utils
$packer btop
$packer cliphist
$packer code
$packer cpupower
$packer cups
$packer cups-filters
$packer cups-pdf
$packer dosfstools
$packer duf
$packer dunst
$packer efibootmgr
$packer efitools
$packer egl-wayland
$packer f2fs-tools
$packer feh
$packer ffmpegthumbnailer
$packer file-roller
$packer firefox
$packer firefox-i18n-pl
$packer flameshot
$packer floorp-bin
$packer foot
$packer gcolor3
$packer ghostscript
$packer gimp
$packer git
$packer github-cli
$packer gnome-disk-utility
$packer gparted
$packer grimblast-git
$packer grub
$packer grub-customizer
$packer grub-hook
$packer gsfonts
$packer guestfs-tools
$packer gutenprint
$packer gvfs
$packer hdparm
$packer htop
$packer hwdetect
$packer hwinfo
$packer hyprland
$packer hyprpicker
$packer hyprutils
$packer i3lock
$packer inetutils
$packer intel-compute-runtime
$packer intel-media-driver
$packer intel-oneapi-compiler-shared-runtime
$packer intel-ucode
$packer iptables
$packer iwd
$packer kitty
$packer less
$packer libreoffice-fresh
$packer libreoffice-fresh-pl
$packer logrotate
$packer lsb-release
$packer lsd
$packer lxappearance
$packer mako
$packer man-db
$packer man-pages
$packer mc
$packer meld
$packer mesa
$packer mesa-utils
$packer mkinitcpio-firmware
$packer neovim
$packer network-manager-applet
$packer networkmanager
$packer networkmanager-openvpn
$packer nitrogen
$packer ntfs-3g
$packer ntp
$packer numlockx
$packer nwg-look
$packer openssh
$packer os-prober
$packer pacman-contrib
$packer pamixer
$packer parcellite
$packer papirus-icon-theme
$packer paru
$packer pavucontrol
$packer pdfarranger
$packer perl
$packer picom
$packer pipewire-alsa
$packer pipewire-pulse
$packer plocate
$packer polkit-gnome
$packer poppler-glib
$packer power-profiles-daemon
$packer qemu-full
$packer qemu-img
$packer qt5ct
$packer ranger
$packer reflector
$packer ripgrep
$packer rofi-emoji
$packer rsync
$packer sane
$packer scrot
$packer sddm
$packer simple-scan
$packer slurp
$packer soundconverter
$packer starship
$packer stow
$packer swappy
$packer swaybg
$packer swaylock-effects-git
$packer swaylock-fancy-git
$packer sxhkd
$packer sxiv
$packer system-config-printer
$packer tela-circle-icon-theme-dracula
$packer texinfo
$packer thunar
$packer thunar-archive-plugin
$packer thunar-volman
$packer time
$packer timeshift
$packer trash-cli
$packer tree
$packer ttf-jetbrains-mono-nerd
$packer ttf-meslo-nerd
$packer ttf-noto-nerd
$packer tumbler
$packer ueberzug
$packer unrar
$packer unzip
$packer upower
$packer usbutils
$packer vim
$packer vlc
$packer vulkan-intel
$packer waybar
$packer wget
$packer which
$packer wl-clipboard
$packer wlogout
$packer wofi
$packer wpa_supplicant
$packer xclip
$packer xdg-desktop-portal-hyprland
$packer xdg-user-dirs
$packer xf86-input-synaptics
$packer xf86-video-intel
$packer xf86-video-vesa
$packer xreader
$packer xorg.0.7-1.1
$packer yazi
$packer zathura
$packer zathura-pdf-mupdf
$packer zoxide

paru bibata-cursor-theme
#paru brother-dcp1610w
#paru brscan4
#paru github-desktop-bin

sudo fc-cache -fv &
sudo chsh $USER -s /usr/bin/fish
