## APPEARANCE
#
general {
    gaps_in = 3
    gaps_out = 5
    border_size = 2
    col.active_border = rgba(cdd6f4aa)
    #col.inactive_border = rgba(66333333)
    col.inactive_border = rgba(414868aa)

    layout = master # master|dwindle
}

decoration {
    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0
    rounding = 2
    blur {
        enabled = false
        size = 15
        passes = 2 # more passes = more resource intensive.
        new_optimizations = true
        xray = true
        ignore_opacity = true
    }

    drop_shadow = false
    shadow_range = 4
    shadow_render_power = 3
    shadow_ignore_window = true

    dim_inactive = false
    col.shadow = rgba(1a1a1aee)
}

# Blur for waybar
#blurls = waybar

