## KEYBINDS PROGRAMS
#
# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER
#
# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, RETURN, exec, kitty
bind = $mainMod, X, exec, kitty
bind = $mainMod, E, exec, pcmanfm
bind = $mainMod, W, exec, google-chrome-stable
bind = $mainMod, C, exec, galculator
bind = $mainMod SHIFT, Z, exec, alacritty -e nvim ~/.config/hypr/keybind.md
bind = $mainMod SHIFT, A, exec, azote
bind = $mainMod SHIFT, B, exec, waypaper
bind = $mainMod SHIFT, U, exec, kitty -e yay
bind = $mainMod, Print, exec, grim -g "$(slurp)" - | swappy -f -
bind = $mainMod, Q, killactive,
bind = $mainMod SHIFT, M, exit,
bind = $mainMod, S, exec, $HOME/.config/hypr/scripts/rofi-cliphist
bind = $mainMod, I, exec, $HOME/.config/hypr/scripts/rofi-wifi-menu.sh
bind = $mainMod SHIFT, Q, exec, $HOME/.config/hypr/scripts/rofi-power-menu.sh
bind = $mainMod, V, togglefloating,
bind = $mainMod, D, exec, rofi -show drun
bind = $mainMod CTRL, D, exec, rofi -show run
#bind = $mainMod SHIFT, D, exec, rofi -show combi -modi window,run,combi -combi-modi window,run
bind = $mainMod SHIFT, D, exec, wofi
bind = $mainMod, F, fullscreen
bind = $mainMod, Y, pin
#bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle

bind = $mainMod, K, togglegroup,
bind = $mainMod, Tab, changegroupactive, f

bind = $mainMod SHIFT, G,exec,hyprctl --batch "keyword general:gaps_out 5;keyword general:gaps_in 3"
bind = $mainMod , G,exec,hyprctl --batch "keyword general:gaps_out 0;keyword general:gaps_in 0"

# Volume control
bind=,XF86AudioLowerVolume,exec,pamixer -ud 3 && pamixer --get-volume > /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob
bind=,XF86AudioRaiseVolume,exec,pamixer -ui 3 && pamixer --get-volume > /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob
# mute sound
bind=,XF86AudioMute,exec,amixer sset Master toggle | sed -En '/\[on\]/ s/.*\[([0-9]+)%\].*/\1/ p; /\[off\]/ s/.*/0/p' | head -1 > /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob

# Playback control
bind=,XF86AudioPlay,exec, playerctl play-pause
bind=,XF86AudioNext,exec, playerctl next
bind=,XF86AudioPrev,exec, playerctl previous

# Screen brightness
bind = , XF86MonBrightnessUp, exec, brightnessctl s +5%
bind = , XF86MonBrightnessDown, exec, brightnessctl s 5%-

