## SETTINGS
#
# Input configuration
#
input {
    #kb_layout = us,ru
    kb_layout = pl
    kb_variant =
    kb_model =
    #kb_options = grp:caps_toggle,grp_led:caps,altwin:swap_alt_win,ctrl:rctrl_ralt
    kb_options =
    kb_rules =

    follow_mouse = 2 # 0|1|2|3
    float_switch_override_focus = 2
    numlock_by_default = true
    touchpad {
        natural_scroll = no
        disable_while_typing = false
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}


# Layout configuration
# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    no_gaps_when_only = false
    force_split = 0
    special_scale_factor = 0.8
    split_width_multiplier = 1.0
    use_active_for_splits = true
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    no_gaps_when_only = false
    new_status = master
    special_scale_factor = 0.5
    mfact = 0.5
}

misc {
    #disable_autoreload = true
    disable_hyprland_logo = true
    always_follow_on_dnd = true
    layers_hog_keyboard_focus = true
    animate_manual_resizes = false
    enable_swallow = true
    swallow_regex =
    focus_on_activate = true
    vfr = 1
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
}

# Gestures configuration
#
gestures {
     workspace_swipe = true
     workspace_swipe_fingers = 4
     workspace_swipe_distance = 250
     workspace_swipe_invert = true
     workspace_swipe_min_speed_to_force = 15
     workspace_swipe_cancel_ratio = 0.5
     workspace_swipe_create_new = false
}

# Mouse configuration
#
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

# Idle configuration
#
# exec-once = swayidle -w timeout 300 'swaylock -f -c 313244' before-sleep 'swaylock -f -c 313244'


# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf
