## STARTUP
#
exec-once = waybar -c .config/waybar/config-hypr &
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec-once = xhost +SI:localuser:root &
exec-once = bash -c "mkfifo /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob && tail -f /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob | wob & disown" &
exec-once = mako &
exec-once = nm-applet --indicator &
exec-once = blueman-applet &
exec-once = xrdb ~/.Xresources &
exec-once = wl-paste --watch cliphist store &
exec-once = udiskie &
exec-once = waypaper --restore
# exec-once = ~/.azotebg-hyprland
# exec-once = swaybg -o \* -i ~/Obrazy/BG/world.png -m fill
# exec-once = systemctl --user start hyprpolkitagent
# exec-once = fcitx5 -d &
